version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /home/ubuntu/server
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/initialize.sh
      timeout: 120
      runas: root
  
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
