version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

permissions:
  - object: /home/ubuntu/server
    pattern: "**"
    except: [".env"]
    owner: mars
    group: server
    mode: 644

hooks:
  AfterInstall:
    - location: script/execute.sh
      timeout: 300
